### ISSUE TITLE
Not compatible with 1.12.2

### ISSUE THREAD

**Issue by faeldray** [RedPer/MC-Auto-Sprint-Mod#1]
This mod appears to no longer be compatible with Minecraft 1.12.2. I don't know why this started happening now...I'm pretty sure it was working just the other week.

![image](https://user-images.githubusercontent.com/967709/39389824-e9cce9a2-4a51-11e8-85da-9dfa1b78d693.png)

**Comment by RedPer** [comment]
I don't think I've ever added 1.12.2 to supported versions before. I fixed this in c614746 and compiled just now. It should be on curseforge by now.

**Comment by MaxLevs** [comment]
Still unsupported for me
